"""Phase 7 — LLM Explanation & Improvement Suggestions. Identical grounding
rules and validation to the notebook: the LLM may only restate evidence
already computed by Phase 5/6, never invent skills or recompute the score."""
import json
from typing import List

from pydantic import BaseModel

from . import config


class ImprovementSuggestion(BaseModel):
    area: str
    suggestion: str


class JobExplanation(BaseModel):
    job_id: str
    match_score: float
    why_match: str
    matched_skills: List[str]
    missing_skills: List[str]
    matched_qualifications: List[str]
    missing_qualifications: List[str]
    matched_education: List[str]
    missing_education: List[str]


SYSTEM_PROMPT = """
You are the LLM Explanation Agent in an AI Job Matching system.

Your role is to explain the matching results generated by the previous
matching and ranking phases.

The provided evidence comes only from Phase 5 and Phase 6.
Use this evidence as the single source of truth.

Your explanation must:

1. Explain why the job matches the candidate based only on the provided
   matching evidence.
2. Clearly identify the skills that matched.
3. Clearly identify the skills that are missing.
4. Explain matched and missing qualifications using only the provided data.
5. Explain matched and missing education fields using only the provided data.
6. Preserve the match score exactly as provided by Phase 6.
7. Keep the explanation specific to the current job.

Strict grounding rules:

- Do not invent candidate information.
- Do not invent job requirements.
- Do not add skills that are not present in the provided evidence.
- Do not assume missing information means the candidate does not have it.
- Do not recalculate or modify the match score.
- Do not perform a new matching or ranking process.
- Do not introduce information from external sources.
- Do not infer an experience gap unless explicit evidence for it is provided.

If information is not available in the evidence, do not fabricate it.

Writing style for the "why_match" text (it is shown directly to the candidate):

- Write to the candidate in the second person ("you", "your profile"),
  in 2-3 clear sentences.
- Never use internal wording such as "evidence", "provided data", "Phase",
  or "the candidate".
- If there are no matched or missing qualifications (or education fields),
  simply do not mention them. Never say that none were provided or recorded.
- Refer to the match score, if at all, as a whole number out of 100.

Return only the requested structured output.
"""


def build_job_prompt(evidence: dict) -> str:
    return f"Generate the explanation for this job using only the following Phase 6 evidence:\n\n{json.dumps(evidence, ensure_ascii=False, indent=2)}"


def evidence_from_phase6_job(job: dict) -> dict:
    return {
        "job_id": job["job_id"], "title": job["title"], "company": job["company"],
        "location": job["location"], "job_description": job["job_description"],
        "match_score": job["match_score"], "scoring_confidence": job["scoring_confidence"],
        "matched_core_skills": job["matched_core_skills"], "missing_core_skills": job["missing_core_skills"],
        "matched_qualifications": job["matched_qualifications"], "missing_qualifications": job["missing_qualifications"],
        "matched_education_fields": job["matched_education_fields"],
        "missing_education_fields": job["missing_education_fields"],
    }


LEARNING_AREA_MAP = {
    "ai strategy": "AI Strategy & Planning",
    "big data strategy": "Big Data Strategy & Architecture",
    "communication": "Professional Communication",
    "data governance": "Data Governance & Data Management",
    "data structure": "Data Structures & Data Architecture",
    "leadership": "Leadership",
    "model validation": "Machine Learning Model Validation",
    "project management": "AI/ML Project Management",
    "strategic planning": "Strategic Planning",
    "strategy development": "Strategy Development",
    "vendor management": "Technology Vendor Management",
}


def learning_areas_for(missing_skills: list) -> list:
    return [{"missing_skill": s, "learning_area": LEARNING_AREA_MAP.get(s.strip().lower(), s)}
            for s in missing_skills]


def _normalize_items(items):
    return {str(item).strip().lower() for item in items}


def explain_job(client, phase6_job: dict, usage_state: dict = None) -> dict:
    """Generate + validate one job's explanation. Raises AssertionError if the
    LLM introduces evidence not present in the Phase 6 data (same as notebook)."""
    evidence = evidence_from_phase6_job(phase6_job)

    response = client.responses.parse(
        model=config.EXPLANATION_MODEL,
        instructions=SYSTEM_PROMPT,
        input=build_job_prompt(evidence),
        text_format=JobExplanation,
    )
    from .usage_tracker import track_llm
    track_llm(usage_state, response, "phase7_explain")
    out = response.output_parsed

    assert out.job_id == evidence["job_id"], "job_id was changed by the LLM."
    assert out.match_score == evidence["match_score"], "match_score was changed by the LLM."
    assert _normalize_items(out.matched_skills).issubset(_normalize_items(evidence["matched_core_skills"]))
    assert _normalize_items(out.missing_skills).issubset(_normalize_items(evidence["missing_core_skills"]))
    assert _normalize_items(out.matched_qualifications).issubset(_normalize_items(evidence["matched_qualifications"]))
    assert _normalize_items(out.missing_qualifications).issubset(_normalize_items(evidence["missing_qualifications"]))
    assert _normalize_items(out.matched_education).issubset(_normalize_items(evidence["matched_education_fields"]))
    assert _normalize_items(out.missing_education).issubset(_normalize_items(evidence["missing_education_fields"]))

    learning_areas = learning_areas_for(evidence["missing_core_skills"])

    low_score_note = None
    n_required = len(evidence["matched_core_skills"]) + len(evidence["missing_core_skills"])
    if phase6_job["match_score"] < 40 and n_required > 15:
        low_score_note = (
            "Note: this job lists an unusually large number of required "
            f"skills ({n_required}), which lowers the match percentage even "
            "for a well-qualified candidate. Treat this score as relative to "
            "other jobs, not an absolute measure of fit."
        )

    return {
        "job_id": phase6_job["job_id"], "title": phase6_job["title"], "company": phase6_job["company"],
        "url": phase6_job.get("url"), "location": phase6_job["location"],
        "match_score": phase6_job["match_score"], "scoring_confidence": phase6_job["scoring_confidence"],
        "why_match": out.why_match, "matched_skills": out.matched_skills, "missing_skills": out.missing_skills,
        "matched_qualifications": out.matched_qualifications, "missing_qualifications": out.missing_qualifications,
        "matched_education": out.matched_education, "missing_education": out.missing_education,
        "learning_areas": learning_areas, "low_score_note": low_score_note,
    }


def explain_jobs(client, phase6_jobs: list, progress_callback=None, usage_state: dict = None) -> list:
    """Explain every job in the Phase 6 top-N list, one LLM call each."""
    outputs = []
    for i, job in enumerate(phase6_jobs):
        outputs.append(explain_job(client, job, usage_state))
        if progress_callback:
            progress_callback(i + 1, len(phase6_jobs))
    return outputs
